// src/js/constants/action-types.js
export const LANGUAGE_CHANGED = 'LANGUAGE_CHANGED';

export const MINESWEEPER = {
    RESET_GAME: 'RESET_GAME',
    UPDATE_GAME_TIME: 'UPDATE_GAME_TIME',
    CHANGE_GAME_SETTINGS: 'CHANGE_GAME_SETTINGS',
    PROCESS_USER_FIELD_ACTION: 'PROCESS_USER_FIELD_ACTION',
};
