// src/js/constants/action-types.js
export const LANGUAGE_CHANGED = 'LANGUAGE_CHANGED';

export const MINESWEEPER = {
    RESET_GAME: 'RESET_GAME',
    UPDATE_GAME_TIME: 'UPDATE_GAME_TIME',
    CHANGE_GAME_SETTINGS: 'CHANGE_GAME_SETTINGS',
    PROCESS_LEFT_CLICK: 'PROCESS_LEFT_CLICK',
    PROCESS_RIGHT_CLICK: 'PROCESS_RIGHT_CLICK',
};